In [1]:
import pandas as pd
import requests
import sqlite3

In [2]:
sales_df = pd.read_csv("../data/sales.csv")

print("Nombre de lignes :", len(sales_df))

sales_df.head()

Nombre de lignes : 5

    product  quantity  price        date
0    Laptop         2   1200  2026-07-20
1     Mouse         5     20  2026-07-20
2  Keyboard         3     50  2026-07-21
3   Monitor         1    300  2026-07-21
4    Laptop         2   1200  2026-07-20

In [3]:
import requests
import pandas as pd

url = "https://fakestoreapi.com/products"

response = requests.get(url)

api_data = response.json()

api_df = pd.DataFrame(api_data)

print("Nombre de produits :", len(api_df))

api_df.head()

Nombre de produits : 20

,id,title,price,description,category,image,rating
0,1,"Fjallraven - Foldsack No. 1 Backpack, Fits 15 ...",109.95,Your perfect pack for everyday use and walks i...,men's clothing,https://fakestoreapi.com/img/81fPKd-2AYL._AC_S...,"{'rate': 3.9, 'count': 120}"
1,2,Mens Casual Premium Slim Fit T-Shirts,22.30,"Slim-fitting style, contrast raglan long sleev...",men's clothing,https://fakestoreapi.com/img/71-3HjGNDUL._AC_S...,"{'rate': 4.1, 'count': 259}"
2,3,Mens Cotton Jacket,55.99,great outerwear jackets for Spring/Autumn/Wint...,men's clothing,https://fakestoreapi.com/img/71li-ujtlUL._AC_U...,"{'rate': 4.7, 'count': 500}"
3,4,Mens Casual Slim Fit,15.99,The color could be slightly different between ...,men's clothing,https://fakestoreapi.com/img/71YXzeOuslL._AC_U...,"{'rate': 2.1, 'count': 430}"
4,5,John Hardy Women's Legends Naga Gold & Silver ...,695.00,"From our Legends Collection, the Naga was insp...",jewelery,https://fakestoreapi.com/img/71pWzhdJNwL._AC_U...,"{'rate': 4.6, 'count': 400}"

In [4]:
import sqlite3
import pandas as pd

# Connexion à la base SQLite
conn = sqlite3.connect("../data/company.db")

# Lire la table employees
employees_df = pd.read_sql_query(
    "SELECT * FROM employees",
    conn
)

print("Nombre d'employés :", len(employees_df))

employees_df.head()

Nombre d'employés : 4

   id     name department  salary
0   1      Ali         IT  7000.0
1   2     Sara      Sales  5500.0
2   3  Youssef         HR  5000.0
3   4    Amine    Finance  6500.0