In [1]:
import pandas as pd
import requests
import sqlite3

In [2]:
# CSV
sales_df = pd.read_csv("../data/sales.csv")

# API
url = "https://fakestoreapi.com/products"
api_df = pd.DataFrame(requests.get(url).json())

# SQLite
conn = sqlite3.connect("../data/company.db")
employees_df = pd.read_sql_query("SELECT * FROM employees", conn)

In [3]:
print("Avant :", len(sales_df))

# Supprimer les doublons
sales_df = sales_df.drop_duplicates()

# Supprimer les valeurs manquantes
sales_df = sales_df.dropna()

# Convertir la date
sales_df["date"] = pd.to_datetime(sales_df["date"])

print("Après :", len(sales_df))

sales_df.head()

Avant : 5
Après : 4

    product  quantity  price       date
0    Laptop         2   1200 2026-07-20
1     Mouse         5     20 2026-07-20
2  Keyboard         3     50 2026-07-21
3   Monitor         1    300 2026-07-21

In [4]:
api_df = api_df[["id", "title", "price", "category"]]

api_df = api_df.rename(columns={
    "title": "product"
})

api_df = api_df.drop_duplicates()

api_df = api_df.dropna()

api_df.head()

,id,product,price,category
0,1,"Fjallraven - Foldsack No. 1 Backpack, Fits 15 ...",109.95,men's clothing
1,2,Mens Casual Premium Slim Fit T-Shirts,22.30,men's clothing
2,3,Mens Cotton Jacket,55.99,men's clothing
3,4,Mens Casual Slim Fit,15.99,men's clothing
4,5,John Hardy Women's Legends Naga Gold & Silver ...,695.00,jewelery

In [5]:
employees_df = employees_df.drop_duplicates()

employees_df = employees_df.dropna()

employees_df.head()

   id     name department  salary
0   1      Ali         IT  7000.0
1   2     Sara      Sales  5500.0
2   3  Youssef         HR  5000.0
3   4    Amine    Finance  6500.0